trigger: none

pool:
  name: LinuxPool

variables:
  FRONTEND_IMAGE: 'dhanu0395/project-frontend'
  BACKEND_IMAGE: 'dhanu0395/project-backend'
  TAGS: $(Build.BuildId) 

stages:              
  - stage: Docker
    displayName: "Build, Push, and Run Docker Images"
    jobs:
      - job: DockerBuildPushRun
        steps:
          - checkout: self      

          - task: Docker@2
            displayName: 'Build & Push Backend Image'
            inputs:
              containerRegistry: 'docker0395'
              repository: $(BACKEND_IMAGE)
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              buildContext: .
              tags: |
                $(tags)

          - task: Docker@2
            displayName: 'Build & Push Frontend Image'
            inputs:
              containerRegistry: 'docker0395'
              repository: $(FRONTEND_IMAGE)
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              buildContext: .
              tags: |
                $(tags)
          
          - script: |
              echo "Running container..."
              docker run -d -p 8085:8080 --name backend29 $(BACKEND_IMAGE):$(TAGS)
              sleep 10
              docker ps
            displayName: "Run Backend Container"

           # 🐳 Run Frontend container (with BACKEND env)
          - script: |
              echo "Starting frontend container..."
              docker run -d --name frontend29 -e BACKEND=http://localhost:8085 -p 8084:8080 $(FRONTEND_IMAGE):$(TAGS)
            displayName: "Run Frontend Container"


