trigger: none

pool:
  name: LinuxPool

variables:
  FRONTEND_IMAGE: 'dhanu0395/project-frontend'
  BACKEND_IMAGE: 'dhanu0395/project-backend'
  TAGS: $(Build.BuildId) 

stages:              
  - stage: Docker
    displayName: "Build, Push, and Run Docker Images"
    jobs:
      - job: DockerBuildPushRun
        steps:
          - checkout: self      

          - task: Docker@2
            displayName: 'Build & Push Backend Image'
            inputs:
              containerRegistry: 'docker0395'
              repository: $(BACKEND_IMAGE)
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              buildContext: .
              tags: |
                $(tags)

          - task: Docker@2
            displayName: 'Build & Push Frontend Image'
            inputs:
              containerRegistry: 'docker0395'
              repository: $(FRONTEND_IMAGE)
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              buildContext: .
              tags: |
                $(tags)
          
          - script: |
              echo "Creating Docker network if it doesn't exist..."
              docker network inspect project-network >/dev/null 2>&1 || docker network create project-network

              echo "Running backend container..."
              docker run -d -p 8085:8080 --name backend29 --network project-network $(BACKEND_IMAGE):$(TAGS)
              sleep 10
              docker ps
            displayName: "Run Backend Container"

          - script: |
              echo "Running frontend container..."
              docker run -d --name frontend29 --network project-network -e BACKEND=http://backend29:8080 -p 8084:8080 $(FRONTEND_IMAGE):$(TAGS)
              docker ps
            displayName: "Run Frontend Container"



